syntax = "proto3";

import "google/protobuf/empty.proto";

option java_multiple_files = true;
package ru.karpenko;

message MatrixRow {
    repeated int32 values = 1;
}

message TaskRequest {
    int32 matrixSize = 1;
    int32 pathLength = 2;
    repeated MatrixRow adjacencyMatrix = 3;
}

message TaskResponse {
    string taskId = 1;
}

message DistributorTaskRequest {
    string taskId = 1;
    string subtaskId = 2;
    bytes jarData = 3;
    bytes baseData = 4;
    bytes subTaskData = 5;
}

message ResultResponse {
    string taskId = 1;
    bytes resultData = 2;
}

service GridService {
    rpc addTask(TaskRequest) returns (TaskResponse);
    rpc sendResult(ResultResponse) returns (google.protobuf.Empty);
}

service DistributorService {
    rpc addTask(DistributorTaskRequest) returns (TaskResponse);
}

service ClientService {
    rpc sendResult(ResultResponse) returns (google.protobuf.Empty);
}