syntax = "proto3";
option java_multiple_files = true;
option java_package = "ru.karpenko";
package ru.karpenko;

message MatrixRow {
    repeated int32 values = 1;
}

message TaskRequest {
    int32 matrixSize = 1;
    int32 pathLength = 2;
    repeated MatrixRow adjacencyMatrix = 3;
}

message TaskResponse {
    string taskId = 1;
}

message SubTaskRequest {
    string taskId = 1;
    bytes subTaskData = 2;
    bytes jarData = 3;
}

message SubTaskResponse {
    bytes resultData = 1;
}

message ResultRequest {
    string taskId = 1;
}

message ResultResponse {
    bytes resultData = 1;
}

message DistributorTaskRequest {
    string taskId = 1;
    bytes jarData = 2;
    bytes baseData = 3;
    bytes subTaskData = 4;
}

service GridService {
    rpc addTask(TaskRequest) returns (TaskResponse);
    rpc getNextSubTask(SubTaskRequest) returns (SubTaskResponse);
    rpc getResult(ResultRequest) returns (ResultResponse);
}

service DistributorService {
    rpc addTask(DistributorTaskRequest) returns (TaskResponse);
    rpc getResult(ResultRequest) returns (ResultResponse);
}
